### PR TITLE
FollowEntity and FollowEntities

### PR DESCRIPTION
**Pull request by StijnSimons**
This was all basically control c, control v but aight.
Requested in #552

### CODE REVIEW

**Comment by StijnSimons** [comment]
#523 too i forgot

**Comment by leijurv** [comment]
So this works like `followentity pig`?

**Comment by StijnSimons** [comment]
Yup

**Comment by leijurv** [comment]
That actually works?!

**Comment by StijnSimons** [comment]
Yeah i was surprised it worked too.

**Comment by leijurv** [comment]
Maybe add something rarted where it removes the final letter if it's an S? I know for a fact some people will do followentity pigs

**Comment by StijnSimons** [comment]
Alright will do

**Comment by StijnSimons** [comment]
Actually, since it already uses 
```java
if ((entityName.contains(name) || name.contains(entityName)))
```
it should already pick up pigs etc.

**Comment by leijurv** [comment]
Can u check

**Comment by StijnSimons** [comment]
Yup, works. (Pig is behind me btw)
image

**Comment by Scarbrine** [comment]
I cant get the followentity command to work

**Pull request merged**
