### PR TITLE
Adding a top command

### PR DESCRIPTION
**Pull request by StijnSimons**
Still work in progress; just wanted to make the PR.

### CODE REVIEW

**Comment by StijnSimons** [comment]
Should be ready to go now

**Comment by 0-x-2-2** [comment]
this is pozzed

**Comment by IdanHo** [comment]
You could optimise this by going from 255 downwards and break on an air block (instead of doing 255 checks everytime), also why does this commit have "followentity" added to the help page

**Comment by StijnSimons** [comment]
Because it wasnnt added to my previous PR.

**Comment by 0-x-2-2** [comment]
this seems flawed. what about the nether roof or a 1x1 or a non solid block lol

**Comment by Deauthorized** [comment]
adding a #surface alias would be cool as well

**Comment by CDAGaming** [comment]
All review comments addressed in #1959, recommended for re-review

**Comment by dominikaaaa** [comment]
I'm closing this in favor of #1959 as they seem to accomplish the same thing but this one is less effective.

**Pull request closed without merging**
