### PR TITLE
[Added] Middle mouse click option to select goal

### PR DESCRIPTION
**Pull request by Fefect**
Small improvement from #721 
As an alternative from dragging with left mouse button (incase the position cannot be selected easily in one go).
Goal selection with middlemouse button while in click mode

### CODE REVIEW

**Comment by StijnSimons** [comment]
I’m quite sure you can just click a block and it’ll path there.

**Comment by leijurv** [comment]
i'm not seeing the benefit here?

you can left click a single block right now, this just adds an option to middle click to the same effect...?

**Comment by SIGSTACKFAULT** [comment]
Really, there should be a keybind to set the goal to where your're looking _at any time._

**Comment by jonnyawsom3** [comment]
> Really, there should be a keybind to set the goal to where your're looking _at any time._

i presume you mean pathing goal and not digging like they mean

**Comment by leijurv** [comment]
yeah cringe not really useful imo

**Pull request closed without merging**
