### PR TITLE
use ImmutableSet

### PR DESCRIPTION
**Pull request by babbaj**
[redacted]

### CODE REVIEW

**Comment by ZeroMemes** [comment]
Updated OP's post to conform to the Contributor Code of Conduct

**Comment by leijurv** [comment]
this decweases pewfowmance

**Comment by babbaj** [comment]
i literally dont believe you at all

**Comment by babbaj** [comment]
benchmarked it and ImmutableSet is faster, if not the same as HashSet

**Comment by 0-x-2-2** [comment]
👍

**Comment by 0-x-2-2** [comment]
> benchmarked it and ImmutableSet is faster, if not the same as HashSet

> Benchmark                      Mode  Cnt   Score   Error  Units
> SetBenchmark.containsGuava     avgt    9  29.085 ± 1.128  ns/op
> SetBenchmark.containsJavaUtil  avgt    9  31.668 ± 5.234  ns/op

👌

**Comment by ZeroMemes** [comment]
Edited @0-x-2-2's comment to have those epic markdown code blocks!

**Comment by SuperOP535** [comment]
Epic

**Comment by usereewrjrjeejr** [comment]
epic

**Comment by 0-x-2-2** [comment]
merge when?

**Comment by 0-x-2-2** [comment]
MAJOR PERFORMANCE AND CODE IMPROVEMENT AND NOT MERGED!
SAD!

**Comment by 0-x-2-2** [comment]
👌

**Pull request merged**
