### PR TITLE
Just a little fix, you know was coding away and thought, "hey! here is something cool!"

### PR DESCRIPTION
**Pull request by Scribblefoxx**

### CODE REVIEW

**Comment by Cerbiac** [comment]
Definitely needs to be fixed. Not cool.

**Comment by leijurv** [comment]
Blessed pull request

**Comment by Scribblefoxx** [comment]
Just putting the ones next to the zeros my dudes. Much appreciated!

**Comment by SylveonBottle** [comment]
In 1.14 you can climb vines just by holding jump. Also ladders too. May be Baritone can use this?

**Pull request merged**
