### PR TITLE
Spicy stuff (fixing some stuff that was missed and added a "toaster" for epic bread)

### PR DESCRIPTION
**Pull request by RealIndrit**
Added some more info in chat, because normal people with no knowledge in the code wouldn't realise it was clickable lel.

### CODE REVIEW

**Comment by RealIndrit** [comment]
@leijurv Please dont uwu

**Comment by 0-x-2-2** [comment]
this is ugly 🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢

**Comment by RealIndrit** [comment]
i know, will fix later lel

**Comment by 0-x-2-2** [comment]
toasts are just ugly in general. the worse feature added in Minecraft 1.12.2

**Pull request closed without merging**
