### PR TITLE
better sounds + asmr

### PR DESCRIPTION
**Pull request by EvilSourcerer**
more feet em cee asmr

### CODE REVIEW

**Comment by 0-x-2-2** [comment]
Uploaded via github web 👎

**Comment by leijurv** [comment]
i do not want all these different oggs in the commit history, once you're done please rebase onto sounds branch tip, then squash into one commit.

**Comment by ZeroMemes** [comment]
All of your changes should've been from the **sounds** branch **HEAD**, not **master**.

**Comment by leijurv** [comment]
sounds HEAD, sounds TIP whichever

**Pull request closed without merging**
