### PR TITLE
Print a random furry thing on start.

### PR DESCRIPTION
**Pull request by skylykat**
hello i dont know if this works!!1
do the funny and merge this please
uwu~

### CODE REVIEW

**Comment by DoctorBang** [comment]
why though

**Comment by skylykat** [comment]
😡

**Comment by TheAlan404** [comment]
> why though

why not*

**Comment by DoctorBang** [comment]
Because it fails, and your mom

**Comment by skylykat** [comment]
> Because it fails, and your mom

reasons it failed:
i have 0 experience in java
im dumb
im tired
im dumb

**Comment by skylykat** [comment]
forgot one reason:
your mom

**Comment by DoctorBang** [comment]
How dare you leave out the most important reason

**Comment by skylykat** [comment]
i am sorry doctor bnag

**Comment by DoctorBang** [comment]
It's okay, just don't do it again

**Pull request closed without merging**
