### PR TITLE
Center badges and other stuff

### PR DESCRIPTION
**Pull request by Flurrrr**
-center the badges
-re-arrange them to be more organized
-update the Aristois/Impact badges to the correct versions and fix a broken link

### CODE REVIEW

**Review by l1ving — CHANGES_REQUESTED** [review]
this looks awful

**Comment by Flurrrr** [comment]
leijurv told me to pr it so ¯\_(ツ)_/¯

**Comment by l1ving** [comment]
holy shit why would you center the badges i'm currently crying right now :crying_cat_face:

**Comment by Flurrrr** [comment]
whats so bad about centering anyway

**Comment by leijurv** [comment]
> holy shit why would you center the badges i'm currently crying right now 😿

get fucking TROLLED i just centered the badges :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface:

**Pull request closed without merging**
