### PR TITLE
Added Spider, PigZombie and Enderman conditions

### PR DESCRIPTION
**Pull request by StijnSimons**
Third time's a charm.
uwu sorry

### CODE REVIEW

**Comment by 0-x-2-2** [comment]
📸

**Comment by 0-x-2-2** [comment]
violation of https://github.com/cabaletta/baritone/blob/master/CODE_OF_CONDUCT.md smh

**Comment by StijnSimons** [comment]
uwu

**Comment by 0-x-2-2** [comment]
ur banned

**Comment by StijnSimons** [comment]
:(

**Pull request merged**
