### PR TITLE
Update Elytra QOL

### PR DESCRIPTION
**Pull request by overtimepog**
added so ETA is more readable instead of just in seconds :)
added Firework Replenish from inventory
added ETA generator in the elytra behavior, no way to connect it to the eta command, working on it
added auto elytra mending repairing

### CODE REVIEW

**Comment by ZacSharp** [comment]
Can you please create one pull request per feature?

**Comment by overtimepog** [comment]
I can try

**Comment by overtimepog** [comment]
tbh I dont even want the 1.19.4 I want to build for 1.20.1 but I dont know how, any help?

**Comment by ZacSharp** [comment]
You can just build from the 1.20.1 branch instead. Just keep in mind that pull requests should generally be based on the 1.19.4 branch.

**Pull request closed without merging**
