### PR TITLE
fixed the most important command

### PR DESCRIPTION
**Pull request by xTrM-EN**
Added return to not return Invalid Command

### CODE REVIEW

**Comment by leijurv** [comment]
sorry no this is intentionally like this?

when you say `damn` in chat baritone intentionally says `daniel` but still has the `damn` go through to public chat, when `chatControl` is on

lmao

**Comment by fluffapparition** [comment]
Lmao

**Comment by xTrM-EN** [comment]
damn

**Comment by Graicc** [comment]
[Baritone] Daniel

**Pull request closed without merging**
