### PR TITLE
1.21.4

### PR DESCRIPTION
**Pull request by rfresh2**
should be put on new branch

### CODE REVIEW

**Comment by Greenish-toast** [comment]
Sorry, I'm new to github, How do I download this updated file?

**Comment by ZacSharp** [comment]
For the web UI on a pc:
1. Click "View details" on the line saying that leijurv merged this
2. Click "Details" on the "build" line that just appeared
3. Click on "Summary" on the left
4. Download the "Artifacts" file at the bottom
5. Unzip the file you just downloaded

**Comment by PCKing-Setup** [comment]
Excuse me,I'm new to Github.When I downloaded the built file, it showed that the file was out of date, but I still want to use that version. What should I do?

**Comment by ZacSharp** [comment]
@PCKing-Setup see https://github.com/cabaletta/baritone/issues/4594#issuecomment-2831566755

**Comment by Amnessie** [comment]
> For the web UI on a pc:
> 
> 1. Click "View details" on the line saying that leijurv merged this
> 2. Click "Details" on the "build" line that just appeared
> 3. Click on "Summary" on the left
> 4. Download the "Artifacts" file at the bottom
> 5. Unzip the file you just downloaded

It's outdated, we can not download it, please add it to the list.

**Pull request merged**
