### PR TITLE
Fix registry loading when custom registries present

### PR DESCRIPTION
**Pull request by rfresh2**
Resolves mod compat issues including https://github.com/cabaletta/baritone/issues/4526

Should be forward merged up through 1.21 as same issue is present there

### CODE REVIEW

**Comment by ZacSharp** [comment]
Do you perhaps know how to port this to 1.21.3/1.21.4?
Though it seems like pack loading is broken on 1.21 (EDIT: meant 1.21.3/4) anyway (tested 1.21.3 with `tweaker:runClient`, 1.21.3 with `fabric:runClient`, 1.21.4 with `tweaker:runClient`, 1.21.4 with neoforge 21.4.10-beta)

**Comment by rfresh2** [comment]
@ZacSharp 

1.21(.1): https://github.com/rfresh2/baritone/tree/1.21.1-loottable
1.21.3: https://github.com/rfresh2/baritone/tree/1.21.3-loottable
1.21.4: https://github.com/rfresh2/baritone/tree/1.21.4-loottable (same as 1.21.3)

**Comment by rfresh2** [comment]
you can cherry pick and throw in your merge PR's to 1.21.1 + 1.21.3

and then i can rebase 1.21.4 pr on top

**Comment by rfresh2** [comment]
> and then i can rebase 1.21.4 pr on top

nvm leijurv merged 1.21.4 already

**Pull request merged**
