### PR TITLE
Add useMessageTag setting

### PR DESCRIPTION
**Pull request by jdbool**
...and make it function. Uses that 1.19.1 tag bar system.

It could be any 24-bit colour but I just chose the same default light purple.

## Disabled
Screenshot 2023-06-18 at 10 44 53 PM

## Enabled
Screenshot 2023-06-18 at 11 19 54 PM
Screenshot 2023-06-18 at 11 19 58 PM

### CODE REVIEW

**Comment by ZacSharp** [comment]
Well I guess the setting just can't be backwards compatible.

One detail: In my opinion the message tag is just a different type of prefix so there shouldn't be a parameter to toggle it, like there isn't one for `shortBaritonePrefix` either. (i.e. I think it should decide based on the setting directly in `logDirect(logAsToast, components)`).
`logAsToast` is different because it redirects the message to a completely different output channel.

**Comment by jdbool** [comment]
> Well I guess the setting just can't be backwards compatible.
> 
> One detail: In my opinion the message tag is just a different type of prefix so there shouldn't be a parameter to toggle it, like there isn't one for `shortBaritonePrefix` either. (i.e. I think it should decide based on the setting directly in `logDirect(logAsToast, components)`). `logAsToast` is different because it redirects the message to a completely different output channel.

Agreed, updated. Made the setting backward compatible too

**Review by ZacSharp — APPROVED** [review]
Relying on the logger to get the tag right is not ideal, but gotta pick your poison.
Passing the tag in would behave very similarly anyway (relies on the logger to use the tag instead of relying on the logger to add the tag).

**Comment by leijurv** [comment]
that's cool

**Comment by leijurv** [comment]
whoever does the merging up just needs to remember that this is in 1.19.2 and not 1.19.4

**Pull request merged**
