### PR TITLE
Add replantCrops setting

### PR DESCRIPTION
**Pull request by Orinion**
add replantCrops setting, simmilar to replantNetherWart for the other crops.
Usefull to disable when f.E. raiding villiges

### CODE REVIEW

**Comment by leijurv** [comment]
Nice! Can you make two small changes:

We use `{ }` around all blocks in Baritone even if they're only one line, can you add curlies around your two `if`s

When replantCrops is false, this should make it not replant nether wart.  (i.e. nether wart should only be replanted if both replantCrops is true, and replantNetherWart is true)

**Comment by Orinion** [comment]
sure!
And should i update the docs etc. too?

**Comment by leijurv** [comment]
Yes actually, add something to replantNetherWart's documentation saying like `This setting only has an effect when replantCrops is also enabled`

**Comment by leijurv** [comment]
Can you remove the unrelated change to waypoints? (separate pr)

Also for 1.13 and 1.14 we merge in from master, instead of cherry picking separate PRs to each. Thank you though, but only the one to 1.12 will be merged, then we'll merge master overall into 1.13, then that into 1.14.

**Comment by 0-x-2-2** [comment]
cringe pr bruh

**Pull request merged**
