### PR TITLE
Schematica

### PR DESCRIPTION
**Pull request by K9Paradox**
Allow Baritone to read from .Litematic files alongside of .schematic files. Since Litematica is updated to 1.14.4 and is fully working but lacking a way to "print" aka place blocks.

### CODE REVIEW

**Comment by ZeroMemes** [comment]
what the fuck

**Comment by fluffapparition** [comment]
furries are smart too @zeromemes

**Comment by ZeroMemes** [comment]
This PR is further proof to my theory that all furries are braindead as fuck.

**Comment by fluffapparition** [comment]
@ZeroMemes This is a website for developer collaboration. Go jack around on Twitter like a baby if youre going to complain about someone's interests.

**Comment by ZeroMemes** [comment]
lol

**Comment by TheK0tYaRa** [comment]
> This PR is further proof to my theory that all furries are braindead as fuck.

That's a pretty good reason to look like one. No one expects anything smart from you. Until you reveal your true self. But until that's required - OwO *notices your comment* what's this?

**Pull request closed without merging**
