### PR TITLE
hunting

### PR DESCRIPTION
**Pull request by cusscussyt**
can you add a feature where it can hunt mobs and animals like say i need food i could just tell it to hunt for cows also could you add it so it automatically throws out things when full or goto home and have it when you get to 3 bars or hungers it automatically eats if you have food if you could add that i would be very gratful

### CODE REVIEW

**Comment by CesiumCs** [comment]
image

**Comment by l1ving** [comment]
To this day I still won't understand how people manage to fuck up this badly. Like, it takes *several* clicks to make a pull request

**Comment by scorbett123** [comment]
No, you mess up after you have created the pull request by messing with the branch, but to not notice it whilst creating the pull is special.

**Comment by cusscussyt** [comment]
im sorry i dont know how to make a suggestion i was just asking for some things to be added

**Comment by l1ving** [comment]
Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)

**Pull request closed without merging**
