### PR TITLE
Option to ignore direction of certain blocks during building

### PR DESCRIPTION
**Pull request by Entropy5**
Toggling this option will let baritone place glazed terracotta, bone blocks and hay bales freely.
Current behavior (with buildignoreexisting false) often includes continuous breaking and placing the same block, as baritone does not understand how to place a block so it faces the right way.

### CODE REVIEW

**Review by ZacSharp — CHANGES_REQUESTED** [review]
Nice someone actually went ahead and implemented this.
Two things though:
1. Place the check right after the check in `return current.equals(desired);` ([here](https://github.com/cabaletta/baritone/blob/3adfa16db8305a07200b29bcde32e3912699ee79/src/main/java/baritone/process/BuilderProcess.java#L864))
2. Instead of checking for specific blocks you should check whether `current.getBlock() == desired.getBlock()` (you already know `current.equals(desired) == false` because of 1.) and if the blocks are the same, check whether all properties except the rotation match.

**Comment by Entropy5** [comment]
@ZacSharp I tested this and it seems to work without any additional property checks
https://github.com/Entropy5/baritone/commit/32a7657c4ffd933cba4ed8d289e4e6bb32b6cd39
Thoughts?

**Comment by ZacSharp** [comment]
The problem with that approach is that it ignores *all* properties, not just direction so it is definitely not a good implementation for `buildIgnoreDirection`.
On the other hand a setting to ignore any properties might be useful in some cases, because Baritone can't really deal with anything beyond choosing the correct item and properties are often for things that can't be dealt with by choosing a different item (redstone power level, cauldron level, door state, lever flicking, plant groth, etc.). I never used the builder to build non-trivial schematics so I don't know whether such a setting  would help.

**Comment by wagyourtail** [comment]
maybe pull this out to a `buildIgnoreNBT` option or something?

**Comment by Entropy5** [comment]
@ZacSharp I realised this once baritone started placing granite instead of stone
made a new pull request https://github.com/cabaletta/baritone/pull/3159

**Pull request merged**
