### PR TITLE
Fix mine under 0 height

### LINKED ISSUE #4112: 1.20.1 Elytra beta test error
## Some information
Operating system: Windows 10 x64
Java version: 17.0.8 64bit
Minecraft version: 1.20.1 Fabric
Baritone version: Elytra beta test 1.20.1 Fabric
Other mods (if used): 
        - appleskin 2.5.0+mc1.20
	- baritone 1.2.19-572-gfa28a56e
	- betterf3 7.0.1
	- betterstats 2.10.3+1.20.1
	- blackout 1.0.1
	- chesttracker 1.1.22
	- clientcommands 2.8.3
	- cloth-config 11.1.106
	- controlling 12.0.2
	- detailab 2.6.3+1.20.1-fabric
	- draggable_lists 1.0.1
	- emi 1.0.19+1.20.1+fabric
	- emi_loot 0.6.5+1.20.1
	- emojitype 2.2.0+1.20
	- fabric-api 0.87.0+1.20.1
	- fabricloader 0.14.22
	- ferritecore 6.0.0
	- forgeconfigapiport 8.0.0
	- higtools 2.7
	- immediatelyfast 1.1.28+1.20.1
	- indium 1.0.25+mc1.20.1
	- java 17
	- litematica 0.15.3
	- lithium 0.11.2
	- malilib 0.16.1
	- memoryleakfix 1.1.1
	- meteor-client 0.5.4-1907
	- meteor-rejects 0.3
	- meteor-villager-roller 1.4.2+mc1.20.1-rev.ac89621
	- meteorplus 1.20.1-for-dev-build
	- minecraft 1.20.1
	- modelfix 1.14
	- modmenu 7.2.1
	- moonlight 1.20-2.8.4
	- no-telemetry 1.7.0
	- reeses-sodium-options 1.6.4+mc1.20.1-build.94
	- rrls 1.20.1-3.1.1-fabric
	- searchables 1.0.1
	- sodium 0.5.2
	- sodium-extra 0.5.1+mc1.20.1-build.112
	- starlight 1.1.2+fabric.dbc156f
	- viafabricplus 2.8.2
	- xaerominimap 23.6.2
	- xaeroplus 1.20.1
	- xaeros-map-chest-tracker-integration 1.0.1
	- xaeroworldmap 1.33.0

## Exception, error or logs

[latest.log](https://github.com/cabaletta/baritone/files/12411185/latest.log)

## How to reproduce
Use: #mine minecraft:diamond_ore minecraft:deepslate_diamond_ore

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

### PR DESCRIPTION
**Pull request by Nekiplay**
Fix mine under y 0

Fix #4112

### CODE REVIEW

**Comment by ZacSharp** [comment]
How does this fix #4112? Unless I missed something the code you edited is dead.

**Comment by Nekiplay** [comment]
> How does this fix #4112? Unless I missed something the code you edited is dead.

Now it scans ores that are below 0 height and does not cause an error when writing #mine deepslate_diamond_ore at height -1 etc.

**Comment by wagyourtail** [comment]
doesn't account for custom worldheight.
also yeah, this class doesn't do anything anymore...
also this breaks the optimized section search order. and breaks scanning above y 192

the original code did in fact scan below y=0

**Comment by Nekiplay** [comment]
> doesn't account for custom worldheight.
also yeah, this class doesn't do anything anymore...
also this breaks the optimized section search order. and breaks scanning above y 192

> the original code did in fact scan below y=0

image
image

It just walks around and doesn't see the ore. So it doesn't scan below 0

**Comment by wagyourtail** [comment]
deepslate_diamond_ore

**Comment by Nekiplay** [comment]
> deepslate_diamond_ore

Same problem

**Comment by wagyourtail** [comment]
what's your #modified btw

**Comment by Nekiplay** [comment]
> what's your #modified btw

clear #modified
Any execution #mine below 0 height causes an error

**Comment by wagyourtail** [comment]
oh I see what's going on now... did you even look at the stack trace in the logs or test what you wrote.
well this won't fix it... you need to do it in FasterWorldScanner. because @ZacSharp forgot to do the changes that ARE in WorldScanner when porting it up

**Comment by wagyourtail** [comment]
https://github.com/cabaletta/baritone/pull/4145

**Comment by leijurv** [comment]
@ZacSharp just looked at this since you pointed me to it from the comment. Should the intstream now go from 0 to 24 instead of 0 to 16?

**Comment by wagyourtail** [comment]
no. this pr is just wrong. he meant #4145

**Comment by ZacSharp** [comment]
@wagyourtail is right, I messed up tap completion (type "fix mine", select matching issue, screwed).

**Comment by Tendas240** [comment]
> @wagyourtail is right, I messed up tap completion (type "fix mine", select matching issue, screwed).

so is there a fix for that i can download or anything i can do ingame? maybe i should use another baritone version? im just a user. i have no experience with coding or something like that.

**Comment by ZacSharp** [comment]
You can use [CI builds](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=is%3Asuccess+event%3Apush).

**Comment by Tendas240** [comment]
what exactly is that and how do i install it?

 
 

Gesendet: Sonntag, 19. November 2023 um 23:48 Uhr
Von: "ZacSharp" ***@***.***>
An: "cabaletta/baritone" ***@***.***>
Cc: "Tendas240" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [cabaletta/baritone] Fix mine under 0 height (PR #4144)


 

You can use CI builds.

**Pull request closed without merging**
