### PR TITLE
Remove retarded MC field.

### PR DESCRIPTION
**Pull request by 0-x-2-2**
Why would he do this when mc field exists.

### CODE REVIEW

**Comment by StijnSimons** [comment]
XDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD

**Comment by 0-x-2-2** [comment]
> XDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD

This is me when @leijurv makes a commit before I make pr two (2) times.

**Comment by 0-x-2-2** [comment]
HE DID IT AGAIN!

**Comment by StijnSimons** [comment]
i think we should ban leijurv off of this repository for trolling

**Comment by 0-x-2-2** [comment]
He keeps doing it.................

**Comment by 0-x-2-2** [comment]
Yep, its gamer time :)

**Pull request merged**
