### PR TITLE
add itemSaver setting.

### LINKED ISSUE #997: Item Saver Mode
## Describe your suggestion
If a enchanted pickaxe is almost desetroyed 1/XXXX durability, then it should stop using that pickaxe. Also it should be only applied to enchanted pickaxes.

## Settings
A simple boolean to toggle it on and off.

## Context
If you have a good enchanted pickaxe like Efficiency V and Luck III it saves them so you just need to repair them instead of enchant a new one.

## Final checklist
- [  ] I have not used any OwO's or UwU's in this issue.

### LINKED ISSUE #1354: When pathing/tunneling/mining Don't break tools
## Describe your suggestion
If there are multiple pickaxes or other tools in the players inventory Baritone won't use the tool until it breaks and will switch tools at around 50 durability left.

## Settings
#DontBreakTools (Boolean) 
and or
#SwapTools (Boolean)

## Context
This is very useful for when the user may want to have baritone mine for extended periods of time and or excavate huge areas without breaking their precious tools.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

### PR DESCRIPTION
**Pull request by scorbett123**
stops baritone using a item when it gets down to 1 durability.

fixes #997
closes #1354

### CODE REVIEW

**Review by l1ving — APPROVED** [review]

**Comment by Heleilton** [comment]
Hello, can you explain to me how to install this?

(I don't speak English, so forgive me for the grammar )

**Comment by l1ving** [comment]
https://github.com/cabaletta/baritone/blob/master/SETUP.md

**Comment by Heleilton** [comment]
how to specifically install this "the top modification". 
Reading "https://github.com/cabaletta/baritone/blob/master/SETUP.md" with the google translator does not help at all.
 ;-( ._tears_.

sorry i'm a big shit

**Comment by l1ving** [comment]
```
git clone https://github.com/scorbett123/baritone
cd baritone
git checkout toolSaver
./gradlew build
```

**Comment by Heleilton** [comment]
From what you said I did understand anything lol, I don't understand java, english, and this site.

But I was able to understand that as the modifications have to be done in the source, that is, I understood what should be changed and where it should be changed ("source" .zip), however, how I transform a .zip (source) file into .jar?

If I'm pissing you off, send me to hell. = (

**Comment by l1ving** [comment]
> however, how I transform a .zip (source) file into .jar?

I told you how. Run these in a terminal
```
cd baritone
git checkout toolSaver
./gradlew build
```

**Comment by Heleilton** [comment]
I understand. To do this, use the terminal? Is it on this site or is it a specific program?

I've never used google translators so much in my life lol.

**Comment by l1ving** [comment]
A terminal on Linux. Use `gradlew.bat build` instead of `./gradlew build` on Windows.

**Comment by Heleilton** [comment]
I'm doing it, but i have a question, the end result, will it be a mod forge or fabric? I'm using "https://github.com/cabaletta/baritone/releases> v1.6.1> Source code
(zip) "

**Comment by l1ving** [comment]
The Baritone repo is Forge by default.

**Comment by Heleilton** [comment]
and on this walk, the source I took gave 3 errors

package net.minecraft.init does not exist
cannot find symbol class Vec3i
cannot find symbol class Vec3i

Eu desisto rsrs

**Review by Heleilton — COMMENTED** [review]
failed
:compileApiJava
Settings.java
package net.minecraft.init does not exist
cannot find symbol class Vec3i
cannot find symbol class Vec3i #


////////////////////////
21:29:57: Executing task 'prepareRunClient'...

> Task :buildSrc:compileJava UP-TO-DATE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE

> Configure project :
New Dep: com.github.ImpactDevelopment:Vanilla:1.16.2_mapped_snapshot_20200813-1.16.1

> Task :compileApiJava FAILED
C:\Users\helei\Desktop\1\src\api\java\baritone\api\Settings.java:24: error: package net.minecraft.init does not exist
import net.minecraft.init.Blocks;
                         ^
C:\Users\helei\Desktop\1\src\api\java\baritone\api\Settings.java:26: error: cannot find symbol
import net.minecraft.util.math.Vec3i;
                              ^
  symbol:   class Vec3i
  location: package net.minecraft.util.math
C:\Users\helei\Desktop\1\src\api\java\baritone\api\Settings.java:808: error: cannot find symbol
    public final Setting<Vec3i> buildRepeat = new Setting<>(new Vec3i(0, 0, 0));
                         ^
  symbol:   class Vec3i
  location: class Settings
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileApiJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
1 actionable task: 1 executed
21:29:59: Task execution finished 'prepareRunClient'.
///////////////////////

**Comment by scorbett123** [comment]
The issue  that you are having is that you are trying to use the 1.12 branch (master) and compile to 1.16. This unfortunately doesn't work, if you give me a minute I will compile a version for you.

**Comment by scorbett123** [comment]
Here you go:

[toolsSaver (2).zip](https://github.com/cabaletta/baritone/files/5438337/toolsSaver.2.zip)

**Comment by Heleilton** [comment]
Good morning my friend, it opens(any of the versions within "toolsSaver (2).zip), however when entering a world, either solo, or on a server it crashes *

I believe I was not using the master, I was using >>>
https://github.com/cabaletta/baritone/releases/tag/v1.6.1




Crash report*:
[crash-2020-10-26_07.55.27-client.txt](https://github.com/cabaletta/baritone/files/5438466/crash-2020-10-26_07.55.27-client.txt)

**Comment by scorbett123** [comment]
yea, probably running into #2115.

**Comment by Heleilton** [comment]
Why does a single change cause so much trouble?

**Comment by l1ving** [comment]
It doesn't

**Comment by ZacSharp** [comment]
The forge build works just fine for me
Did a rebase onto 1.16 and some changes because of version differences
[dist.zip](https://raw.githubusercontent.com/ZacSharp/uploads/master/cabaletta/baritone/issues/2107/dist.zip)

**Comment by Heleilton** [comment]
> The forge build works just fine for me
> Did a rebase onto 1.16.2 and some changes because of version differences
> [dist.zip](https://raw.githubusercontent.com/ZacSharp/uploads/master/cabaletta/baritone/issues/2107/dist.zip)


Man I love you from the bottom of my heart, your version worked!
Only yours! May the angels bless you kkk.

If you can, to satisfy my curiosity, tell me what you did, I would be even more grateful.

I was unable to compile, much less use what the young man above did.


Valeu negão, tu é o cara, muito obrigado.

**Comment by ZacSharp** [comment]
What I did (for Linux and likely also Mac):
1. get the workspace set up
   * clone the repository of this pull request `git clone https://github.com/scorbett123/baritone.git`
   * change working directory to the new repository `cd baritone`
   * switch to the toolsSaver branch `git checkout toolsSaver`
2. rebase onto newest 1.16.2
   * add the main baritone repository as a remote `git remote add upstream https://github.com/cabaletta/baritone.git`
   * get the branch info for upstream `git fetch upstream`
   * rebase onto 1.16.2 `git rebase upstream/1.16.2`
   * work through all the conflicts until the rebase is done
3. fix the build by adjusting some names that changed between 1.12.2 and 1.16.2
4. build forge distribution `./gradlew build -Pbaritone.forge_build`
5. do some testing to confirm it is working
6. make a zip and upload it here

**Comment by ZacSharp** [comment]
@scorbett123 when testing this I noticed that it still breaks tools whenever they are in slot 0 and there is no other tool on the hotbar  because it uses slot 0 as a fallback.

**Review by ZacSharp — APPROVED** [review]

**Comment by randomairborne** [comment]
can someone merge this? it doesent seem to have issues, and might be useful.

**Comment by l1ving** [comment]
Yes it does, read above.

**Comment by scorbett123** [comment]
@l1ving What issues does it have? I can't find any others mentioned in this pull request.

**Comment by l1ving** [comment]
https://github.com/cabaletta/baritone/pull/2107#issuecomment-717593915

Step 3.

**Comment by l1ving** [comment]
I mean the proper solution is merging this and fixing it upstream

**Comment by scorbett123** [comment]
@l1ving what do you expect me to do to fix this. There is some changes in the code of Minecraft itself. The master branch is 1.12 so  I have written it so it is compatible with 1.12, all of the issues that have been discovered with this are due to the change in syntax from getItemDamage() to getDamage() whilst going from 1.12 to 1.16.

**Comment by scorbett123** [comment]
> I mean the proper solution is merging this and fixing it upstream

That isn't just the proper solution, it is the only solution.

**Comment by randomairborne** [comment]
I changed the getdamage thing, now it hates the l in value for some reason

**Comment by randomairborne** [comment]
fixed, compiles but still breaks tools

**Comment by scorbett123** [comment]
> The forge build works just fine for me
> Did a rebase onto 1.16.2 and some changes because of version differences
> [dist.zip](https://raw.githubusercontent.com/ZacSharp/uploads/master/cabaletta/baritone/issues/2107/dist.zip)

Use this jar then. It works however is slightly outdated.

**Comment by recursivetree** [comment]
I do not encounter the issue mentioned with slot 0. This pull request should be merged anyways, even if there is a small edgecase bug, because it provides a major advantage to baritone. Because I required a tool saver  I found my way here

**Comment by scorbett123** [comment]
@recursivetree The issue has been fixed in my latest commit.

**Comment by scorbett123** [comment]
closes #1354

**Comment by ZacSharp** [comment]
you need to edit that into the initial comment for github to actually link the issue

**Comment by Gorex-alt** [comment]
Hi, i was just wondering if this also works with the fabric 1.16.4 version of baritone. I'm new to all of this so following the conversation was quite hard. What I understood was that there was toolsaver for the forge version and that you needed to do something special to integrate it. Even after reading the article in the link mentionned above I could'nt make anything of it.

Can you help me?

**Comment by scorbett123** [comment]
You would have to build it for fabric, you would probably have to merge it into 1.16 yourself, make sure that you do it onto the 1.16 branch and run it as baritone.fabric_build.

**Comment by Gorex-alt** [comment]
Thank you for your fast reply but i have no clue on how to do it. Is there any chance you could do it for me or give me a tutorial?

**Comment by scorbett123** [comment]
> Thank you for your fast reply but i have no clue on how to do it. Is there any chance you could do it for me or give me a tutorial?

I will just do it for you, it is easier for all of us. Give me a bit.

**Comment by scorbett123** [comment]
[baritone-1.6.2.zip](https://github.com/cabaletta/baritone/files/5932214/baritone-1.6.2.zip)
Here you go, I haven't tested it so if it doesn't work just tell me. You will need to unzip this and place the version you want into your mods folder.

**Comment by Gorex-alt** [comment]
I have tested it for minecraft version 1.16.4 with golden shovels because of their low durability. out of 6 tests I experienced 1 gamecrash (probably due to my pc running autocad on the background). In all of the tests 3 out of 3 shovels were broken. Is there some commandline i have to enter in game before using to change a setting because i didn't know if i had to.

**Comment by scorbett123** [comment]
make sure to enable the itemSaver setting.

**Comment by Gorex-alt** [comment]
After toggeling the itemsaver setting to true the program still broke all 3 shovels. Is it possible that the program saves the tools when they are at 0 durability? If so is there a way to set a specific durability number at witch it saves the tool?

**Comment by Gorex-alt** [comment]
Alright, anyways big thank you for the help, ur a real hero ;)

**Comment by scorbett123** [comment]
@leijurv Is there any reason you aren't merging this? It seems to be wanted.

**Comment by scorbett123** [comment]
Thanks

**Comment by leijurv** [comment]
generally fine to ping me if i've missed something (e.g. if no one has raised any issues and it's been a week or two since the last update) :)

**Comment by PetyXbron** [comment]
### **Can I install the itemsaver for Forge 1.16.5?**

I saw you posted here zip files with Baritone like dit.zip, toolsSaver.2, baritone-1.6.2 and more but these jar files doesn't worked for me, and some of them was for Fabric, so... not useful for me.
There is my process;
 
Downloaded the zip files for 1.16.1 and 1.16.2 and I wanted to try it on 1.16.5, so I installed them in my Forge mods folder and I tried commands like `#itemsaver` or `#toolsaver`, nothing worked.
Using `baritone-api-1.6.1.jar` crashed my game. I tried to create new world, but it didn't helped.
So I installed the first file from zip, the `baritone-1.6.1.jar` didn't worked too, game crashed after joining world/server.

Actually I wanted to install Impact client, but sadly Impact client isn't free for 1.16.5 yet. Let's try the free way without Impact.

**I don't know how you are doing this, but can anyone give me the jar file with toolsaver/itemsaver for Forge 1.16.5 please?**

Can I just use someway the `baritone-api-forge-1.6.3.jar` with itemsaver setting? Please?
It's really sad when you're breaking sand with Baritone and then your netherite shovel breaks with efficency IV and mending....

Im really confused, I don't know why Baritone doesn't add these settings officially for all users. They're soo many, so why don't add more? :D
Can anyone help me, or explain it please?

**Comment by scorbett123** [comment]
It has been merged, so download the latest 1.16 release, at the time out writing this is 1.6.3

**Comment by PetyXbron** [comment]
> It has been merged, so download the latest 1.16 release, at the time out writing this is 1.6.3

Oh yeahh, cool. Github is a complex thing that I still need to learn to use.
So after the that merge, I will just easily download the latest 1.16.5 version and because it's 'merged' I will get the itemsaver/toolsaver setting in the new version, am I right?

**Comment by ZacSharp** [comment]
No, not really. The latest release obviously doesn't contain features newer than the release itself. And in addition it might take a while until a feature is actually ported to the newer mc versions, so the date check only reliably works for master (1.12.2).

Did you check it is released @scorbett123? I can't even find where it was merged upwards.

**Comment by Flurrrr** [comment]
The latest 1.16 release was on February 5th, this was merged the day after, the only other release after 1.6.3 was 1.2.15 which has this, but there are no 1.16 releases with this unfortunately

**Comment by scorbett123** [comment]
Wait, sorry just checked the merge date and assumed it was just before

**Comment by PetyXbron** [comment]
Bruh... :( so that's why I didn't found it in newest version...

**Pull request merged**
