### PR TITLE
Correct Usage specific amount

### PR DESCRIPTION
**Pull request by CesiumCs**
idfk why its `mine 64 diamond_ore` now but i tested it and that's just how it be

### CODE REVIEW

**Review by ZacSharp — APPROVED** [review]

**Review by l1ving — APPROVED** [review]
lol

**Comment by ZacSharp** [comment]
Why did you close this?

**Comment by l1ving** [comment]
leij takes forever to review :/

**Comment by CesiumCs** [comment]
im dropping everything remotely impact related

**Comment by ZacSharp** [comment]
Any reason why I shouldn't recreate this pr myself?

**Pull request closed without merging**
