### PR TITLE
Merge 1.17.1 into 1.18.2

### PR DESCRIPTION
**Pull request by ZacSharp**
Note that this does not contain changes from #3458 
Please don't merge immediately before or after updating 1.17.1 as I'd like to re-merge in that case.

Do you want updates for 1.18.1?

### CODE REVIEW

**Comment by ZacSharp** [comment]
Checks failed because I accidentally made this pr target master and then changed the base branch while they were running.

**Comment by wagyourtail** [comment]
you could try like force pushing or something to get the checks to rerun

**Comment by ZacSharp** [comment]
Okay that definitely did not work as expected.
Now I have a pr desynced from it's origin branch.

**Comment by ZacSharp** [comment]
Now I can't even reopen it because there's no new commits, no matter what's actually pushed to my repo.

**Comment by ZacSharp** [comment]
I don't get it.

**Comment by ZacSharp** [comment]
Seems to be all fine now so I'll leave it as is.
I think the problem was that I pushed a commit that's already in 1.18.2.

**Pull request merged**
