### PR TITLE
Remove container memory

### LINKED ISSUE #2568: #chests (or containerMemory) is broken
## Some information
Operating system: Fedora 32
Java version: 11.0.10
Minecraft version: 1.16.5 (Fabric 0.11.1)
Baritone version: 1.6.3
~~Forge~~ Fabric mods (if used): [AppleSkin](https://github.com/squeek502/AppleSkin), [NBTTooltip](https://github.com/zabi94/NBTTooltip), [Xaero's Minimap](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap) and [Worldmap](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)

## Exception, error or logs

[latest.log](https://github.com/cabaletta/baritone/files/6135909/latest.log) (Despite the folder name, I do *not* have Wurst installed.)

## How to reproduce
1. Run `#set containerMemory true`
2. Open a chest, put things in it, close it
3. Run `#chests`

## Modified settings
- `allowParkour`
- `assumeWalkOnWater`
- `containerMemory`

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and ~~forge~~ fabric mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

-----

I'm aware this is a duplicate of #2511, #2512, and #2513; but the reporter on those invalidated them by failing to follow procedure; I believe this instance is properly-formatted.

### PR DESCRIPTION
**Pull request by scorbett123**
This removes container memory as it is out of scope  for baritone.

closes #2568 (something can't be broken if it's non-existent).

If I have missed any references to it please let me know.

### CODE REVIEW

**Comment by ZacSharp** [comment]
I don't think it is out of scope. It is needed to get materials from chests/shulkers, which in turn has been said to bee a desired feature.

The current implementation is not needed at all though, so I think if someone needs it it's better if they reimplement it.

**Comment by scorbett123** [comment]
yea, it's more that it's not used and doesn't really fit the rest of baritone, it just seems a bit out of place.

**Comment by wagyourtail** [comment]
yeah, feels like more of an altoclef feature imo

**Comment by ZacSharp** [comment]
I don't care whether it could be an altoclef feature or not. Altoclef should not limit the scope of Baritone, especially since it is essentially a whole lot of features that could have ended up being part of Baritone three years ago, if leijurv and brady had finished tenor.
If you start ripping out all features altoclef could cover Baritone will end up being nothing more than its AStarPathFinder, maybe even without path execution.

**Comment by JamesGreen31** [comment]
Altoclef maintainer here.

We are planning on (eventually) doing the storage situation ourselves, so yea I don't think it is that critical for it. Plus, we can always steal it into our fork.

**Pull request merged**
