### PR TITLE
baritoneminecraft.com

### PR DESCRIPTION
**Pull request by BL1Z33**
Let everybody reading the README know that baritoneminecraft.com isn't an official Baritone website.

### CODE REVIEW

**Comment by UltraBlackLinux** [comment]
the website may not be really legitimate but it does link to the github repository instead of providing anything to download.

Also if you start with them you should also incluse 9minecraft and all the shitty other websites, because these actually distribute their own jars it seems

**Comment by BL1Z33** [comment]
> the website may not be really legitimate but it does link to the github repository instead of providing anything to download.
> 
> Also if you start with them you should also incluse 9minecraft and all the shitty other websites, because these actually distribute their own jars it seems.
> 
> Also I don't think it makes much sense to warn somebody from illegitimate downloads if they are already in the github repo. Adding a warning here won't help the 9minecraft users...
> 
> I'd say this is not worth merging.

ill add that, i just saw an issue and no pr so i made one

**Comment by UltraBlackLinux** [comment]
do you not understand? The 9minecraft people are not gonna pin this warning on their baritone download

this won't serve a purpose...

**Comment by scorbett123** [comment]
I think possibly a "downloads from anywhere except the official repo are not official" owtte is fine, however specific name calling isn't as then you really need to call out everyone.

However I'm not entirely sure if this is necessary at all. I'm not actually going to close this as I'm not sure, but I'm doubtful if this is a good change.

**Comment by 0-x-2-2** [comment]
Don't link the websites as that just boosts SEO.

**Pull request closed without merging**
