### PR TITLE
PICKUP_DROPPED - Remove 2nd Items.WHEAT

### PR DESCRIPTION
**Pull request by ZakME**
PICKUP_DROPPED:
Remove 2nd Items.WHEAT
Re-order a few items for neatness

Edit for clarity: Remove duplicate Items.WHEAT

### CODE REVIEW

**Comment by leijurv** [comment]
Why remove wheat...?

**Comment by leijurv** [comment]
If you want this bevahior (ignore wheat) I'd be fine merging a new setting like farmCollectsWheat, but let's not entirely remove it lol

**Comment by ZakME** [comment]
Sorry, I didnt actually remove wheat. You had it coded in twice so I removed the duplicate, the only one left is on line 78/79

**Comment by leijurv** [comment]
LOL my bad

**Pull request merged**
