### PR TITLE
1.21

### PR DESCRIPTION
**Pull request by rfresh2**
~~Fabric working but Forge/NeoForge [still busted](https://github.com/cabaletta/baritone/pull/4347#issuecomment-2099441667) like on 1.20.5/6~~

Tested Fabric + Forge + NeoForge working

### CODE REVIEW

**Comment by StupidRepo** [comment]
Hiya, I tried building for fabric and it froze upon executing `#mine iron_ore`. Just thought I'd let you know :+1:

**Comment by rfresh2** [comment]
@StupidRepo working fine for me

https://github.com/cabaletta/baritone/assets/89827146/b351d369-1e4f-4e69-be56-57f10f3d7700

**Comment by StupidRepo** [comment]
Hm, strange... I'll try again later today. There could be mods conflicting. Some possible ones could be Iris Shaders or Sodium maybe.

**Comment by rfresh2** [comment]
forge + neoforge now working after rebasing on latest 1.20.5 branch

**Comment by gabb1233333333** [comment]
> forge + neoforge now working after rebasing on latest 1.20.5 branch

@rfresh2 
How can i use your version (1,21)?

**Comment by rfresh2** [comment]
> > forge + neoforge now working after rebasing on latest 1.20.5 branch
> 
> @rfresh2 How can i use your version (1,21)?

Download the "Artifacts" from the CI: https://github.com/cabaletta/baritone/actions/runs/9593797633

**Comment by StupidRepo** [comment]
> > > forge + neoforge now working after rebasing on latest 1.20.5 branch
> > 
> > 
> > @rfresh2 How can i use your version (1,21)?
> 
> Download the "Artifacts" from the CI: https://github.com/cabaletta/baritone/actions/runs/9593797633

BTW, this is what I did when I said it crashed.

**Comment by dave9123** [comment]
Is that supposed to be baritoe?

**Comment by pastadudes** [comment]
i sometimes have weird glitching visual artifacts when using 1.21 version tho

**Comment by StupidRepo** [comment]
> *[image hidden because it's so f\*cking big]*
> Is that supposed to be baritoe?

:grimacing: Please keep in mind that you can make a comment on PR commits...

Screenshot 2024-07-04 at 15 12 11

@dave9123

**Comment by ZacSharp** [comment]
Baritoe is indeed the correct mod id.

**Comment by gvf66** [comment]
hello im new how do i download this mod

**Comment by dave9123** [comment]
Clone the repo and build it
________________________________

**Comment by gvf66** [comment]
sorry what does that mean

**Comment by rycbar0** [comment]
as you can write here i assume you already have a github account and are logged in to it.
go to https://github.com/cabaletta/baritone/actions/runs/9593797633 and download the artifacts. unzip the file and copy the baritone jar of your choice to your mods folder

**Comment by dave9123** [comment]
Forgot that exists

**Comment by dave9123** [comment]
Forgot that exists

**Comment by gvf66** [comment]
Screenshot 2024-07-09 090736
did i do this right

**Comment by rycbar0** [comment]
if it works yes else try the one with fabric in the name

**Comment by gvf66** [comment]
will i still need api for that one

**Comment by gvf66** [comment]
sorry that was a dumb question nvm

**Comment by guuuuuug** [comment]
what is the prefix? I tried hashtag and it didn't work

**Comment by Karol532** [comment]
> @StupidRepo working fine for me
> Base.Profile.2024.06.19.-.14.07.57.03.mp4

how to install baritone for 1.21 minecraft java? Yes i am new and i have accidently used 9minecraft page so i need help

**Comment by Karol532** [comment]
> i sometimes have weird glitching visual artifacts when using 1.21 version tho

how to install 1.21 version pls help i am newbie i beg you

**Comment by guuuuuug** [comment]
> > i sometimes have weird glitching visual artifacts when using 1.21 version tho
> 
> how to install 1.21 version pls help i am newbie i beg 

Everything is mentioned above, but don’t forget to take out the .jar file from Artifacts folder

**Comment by Karol532** [comment]
> > > i sometimes have weird glitching visual artifacts when using 1.21 version tho
> > 
> > 
> > how to install 1.21 version pls help i am newbie i beg
> 
> Everything is mentioned above, but don’t forget to take out the .jar file from Artifacts folder

YES IT WORKS, THANK YOU. and i have question. Is this a good page for fabric? ->https://fabricmc.net/use/installer/<-  What should I do if I thoughtlessly downloaded baritone from the 9minecraft website and now I am afraid that I have downloaded some viruses? what is the procedure to protect yourself?

**Comment by wongcallum** [comment]
> What should I do if I thoughtlessly downloaded baritone from the 9minecraft website and now I am afraid that I have downloaded some viruses? what is the procedure to protect yourself?

reinstall windoze

**Comment by dave9123** [comment]
Just run a Windows Defender scan
________________________________

**Comment by ZacSharp** [comment]
@rfresh2 is anything missing to get this merged?

**Comment by rfresh2** [comment]
> @rfresh2 is anything missing to get this merged?

its complete

**Comment by rycbar0** [comment]
can i request a last minute change to baritone.utils.schematic.format.DefaultFormats
```
  LITEMATICA("litematic") {
        @Override
        public IStaticSchematic parse(InputStream input) throws IOException {
            CompoundTag nbt = NbtIo.readCompressed(input, NbtAccounter.unlimitedHeap());
            int version = nbt.getInt("Version");
            switch (version) {
                case 4: //1.12
                case 5: //1.13-1.17
                case 6: //1.18-1.20
                    throw new UnsupportedOperationException("This litematic Version is too old.");
                case 7: //1.21+
                    return new LitematicaSchematic(nbt, false);
                default:
                    throw new UnsupportedOperationException("Unsuported Version of a Litematica Schematic");
            }
        }
    };
```

**Comment by rfresh2** [comment]
> can i request a last minute change to baritone.utils.schematic.format.DefaultFormats

done

**Review by ZacSharp — APPROVED** [review]
There's a generic `RuntimeException` which could be `IllegalArgumentException` and the inline enchantment loops could be factored out, but generally looks fine.

**Comment by Zocyet** [comment]
啊啊啊看不懂英文怎么办？

**Comment by dave9123** [comment]
您可以使用翻译器吗？

**Comment by Greenish-toast** [comment]
Is there still a way to get the 1.21 version for Baritone? the artifacts page has expired.
###### sorry about the necro post

**Comment by rfresh2** [comment]
> Is there still a way to get the 1.21 version for Baritone? the artifacts page has expired.
> ###### sorry about the necro post

you can find latest builds on github actions: https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=branch%3A1.21.1

1.21.1 supports 1.21

**Pull request merged**
