### PR TITLE
1.18 support

### PR DESCRIPTION
**Pull request by wagyourtail**
@leijurv giv me a branch, xd

it works

- [x] - forge 1.18 support

blocks to fix

- [x] - azelea saplings

download artifacts at https://github.com/cabaletta/baritone/actions/runs/1702733433

### CODE REVIEW

**Comment by gagaos** [comment]
Enjoy

**Comment by wagyourtail** [comment]
I'll squash the "empty" commits for updating pre/rc version to build against

**Review by host008 — APPROVED** [review]

**Comment by AidanDevs** [comment]
when trying to build i get this
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.

**Comment by wagyourtail** [comment]
not happening on CI so that's a you problem. (probably wrong version of java or something)

**Comment by AidanDevs** [comment]
Is there anyway one of u guys can just send me the .jar for 1.18 without me having to build, since u guys have already built

**Comment by wagyourtail** [comment]
you can go to [this action](https://github.com/cabaletta/baritone/actions/runs/1531914509) (you need to be signed in) and click the artifacts button (it is recommended to use the baritone-unoptimized-fabric-1.8.0.jar), if you find any bugs please report them to this pull request

**Comment by Bluscream** [comment]
Related PR: https://github.com/gaucho-matrero/altoclef/pull/136

**Comment by gympunknfts** [comment]
Bug found: pathing sees moss blocks as a traversable block when they are actually solid and cannot be walked through.

**Comment by gympunknfts** [comment]
Wait I may have been wrong, the issue may be with azalea instead of moss blocks

**Pull request merged**
