### PR TITLE
1.18.x smooth aim

### PR DESCRIPTION
**Pull request by SM1LLER**
Just implemented SmoothAim from this #2293 and using #3077 made it work on 1.18. Use "#setting smoothAim \<ticks\>". It disabled if set '1'. Ticks is number of ticks baritone will need to rotate camera. It looks laggy, but it's not drops perfomance. Also added waitTicksBeforeAim. Use '#setting waitTicksBeforeAim \<ticks\>'. Ticks is number of ticks baritone will wait before aim new target. It disabled if set '1'. Use this settings carefull with parkour and other things that need fast aim.

Upd. Use this to download artifacts.zip with builded mod https://github.com/SM1LLER/baritone/actions/runs/1774151378

### CODE REVIEW

**Comment by LJS78** [comment]
Hey, I'm kinda new on this website and I don't really understand how to download the mod with SmoothAim, or if I have to edit the file myself? If I have to edit it how can I do that, because there's a lot of files.

**Comment by SM1LLER** [comment]
> Hey, I'm kinda new on this website and I don't really understand how to download the mod with SmoothAim, or if I have to edit the file myself? If I have to edit it how can I do that, because there's a lot of files.

Download artifacts.zip from this page https://github.com/SM1LLER/baritone/actions/runs/1774151378

**Comment by LJS78** [comment]
Thanks!

**Comment by scorbett123** [comment]
I don't know what on earth is going on with the commit history, but it's not right. 

If you are going to create this, please make it on the master branch and then create a pull request onto the master branch.

**Comment by MrLod112** [comment]
Hello You can publish artifacts.zip?

**Comment by TomIsFat** [comment]
> Hello You can publish artifacts.zip?

The earlier one has expired, you can download it here: https://github.com/TomIsFat/baritone/actions/runs/4111294907
(hopefully 1.19.2 will be available

**Pull request closed without merging**
