### PR TITLE
Rawr X3

### PR DESCRIPTION
**Pull request by NoleV2**
[Intro]
Okay, I know this is a really bad idea but
I'm already here so
Here we fuckin’ go
Rawr

[Verse 1]
​x3 nuzzles, pounces on you, uwu you so warm (Ooh)
Couldn't help but notice your bulge from across the floor
Nuzzles your necky wecky-tilde murr-tilde, hehe
Unzips your baggy ass pants, oof baby you so musky
Take me home, pet me, and make me yours and don't forget to stuff me
See me wag my widdle baby tail all for your buldgy-wuldgy
Kissies and lickies your neck
I hope daddy likies
Nuzzles and wuzzles your chest (Yuh)
I be (Yeah) gettin’ thirsty

[Verse 2]
Hey, I got a little itch, you think you can help me?
Only seven inches long, uwu, please adopt me
Paws on your buldge as I lick my lips (UwU, punish me please)
'Bout to hit 'em with this furry shit (He don't see it comin')

### CODE REVIEW

**Comment by cjbrick910** [comment]
Bruh

**Comment by 0-x-2-2** [comment]
🤡

**Comment by StijnSimons** [comment]
github ban lol

**Comment by leijurv** [comment]
did

**Pull request closed without merging**
