### PR TITLE
Merge 1.19.4 into 1.20.2

### PR DESCRIPTION
**Pull request by ZacSharp**
#4112 is the sole reason for this pr. Otherwise I'd wait until there's more things to merge.
EDIT: totally forgot about 91588ca even though I looked at it's diff 30 seconds ago...

### CODE REVIEW

**Comment by ZacSharp** [comment]
Wtf GitHub. I created this pr 3 minutes ago and never added commits, why do you think there's changes I haven't seen yet?
image

**Comment by end-user** [comment]
image

**Comment by ZacSharp** [comment]
Not a problem. Codacy being happy is nice but not required.

**Comment by nicobuzeta** [comment]
@ZacSharp Not sure if it's related to this, but i'm using the build from the CI and i'm getting crash reports from FasterWorldScanner but it appears to be a different location than the original bug. 

Happens when mining below y = 0, but only on a vanilla server with some datapacks. Tested on singleplayer and issue doesn't occur.

I'll attach the relevant log section (no other mods):
[crash.log](https://github.com/cabaletta/baritone/files/13219275/crash.log)


Not sure if I should submit a bug report since I'm using this build, and it hasn't been merged yet.

**Comment by leijurv** [comment]
Hmmm, I'm not sure, maybe we want to merge into 1.20.1 then 1.20.2? But I guess this is okay.

**Comment by ZacSharp** [comment]
I can still make a merge into 1.20.1 if you want to provide more updates for it. Just let me know.
(Also I'd personally like to port new features to 1.12.2 so if you'd like to have them here let me know how I should do it. Like, cherry-pick everything, try merging backwards, or whatever branching strategy)

**Comment by leijurv** [comment]
I personally don't want to deal with 1.12.2 anymore but I'm willing to merge stuff. Make PRs to master, cherry-pick would be good. 👍

**Comment by EmergencyTemporalShift** [comment]
Could this still be merged to 1.20.1? It seems as though that never happened.

**Pull request merged**
