### PR TITLE
Commands

### PR DESCRIPTION
**Pull request by leijurv**
@LoganDark's commands, basically a duplicate of #922. Since it's based off of that branch, github will mark that one as merged once this one is, thankfully.

### CODE REVIEW

**Comment by ZeroMemes** [comment]
Explicit handling of exceptions is superior to implicit bullshit

**Comment by LoganDark** [comment]
a8b1bad NO

That's not there just for reflection or because I randomly felt like it, it's there because you shouldn't obfuscate APIs that are used by other mods.

The command system is SUPPOSED to be extended, and used by other mods or hacked clients.

**Comment by ZeroMemes** [comment]
> [a8b1bad](https://github.com/cabaletta/baritone/commit/a8b1badd8ac7636eace78e5e76b1f9ef44dab2e0) NO
> 
> That's not there just for reflection or because I randomly felt like it, it's there because you shouldn't obfuscate APIs that are used by other mods.
> 
> The command system is SUPPOSED to be extended, and used by other mods or hacked clients. It's not just there for the odd GitHub commit extending Baritone, it's there for _any mod that needs it_, which means it needs to be available, unobfuscated, at runtime.

I removed all reflection usage already, and nothing in API is obfuscated so this isn't an issue.

**Comment by LoganDark** [comment]
> nothing in API is obfuscated so this isn't an issue

Uhhh, that's completely wrong, the API is definitely obfuscated at runtime in the forge jar. Maybe you made a mistake or something but instead of removing that line you could instead repurpose it to encompass the whole API package.

**Comment by ZeroMemes** [comment]
> Uhhh, that's completely wrong, the API is definitely obfuscated at runtime in the forge jar. Maybe you made a mistake or something but instead of removing that line you could instead repurpose it to encompass the whole API package.

API is only obfuscated in standalone, user error.

**Comment by 0-x-2-2** [comment]
😹

**Comment by leijurv** [comment]
logan think about it what point would there be of an api if it were obfuscated lmao

api jar = you get the api (all of it)
standalone jar = you don't (it's obfuscated)

**Comment by LoganDark** [comment]
> user error

Then apparently printing a traceback to chat is user error? Because everything was obfuscated before I added that line to the proguard config.

**Comment by 0-x-2-2** [comment]
Hey, @LoganDark this is the differences for the Baritone jar files.

```
baritone-unoptimized.jar - Largest jar file. - Internal and API code is unobfuscated/unoptimized. - This should not be used. - Worse performance.
baritone-api.jar - Smaller jar file. - Internal code is obfuscated/optimized. - This should be used if you want better performance but also want API access. - Better performance.
baritone-standalone-1.2.9.jar - Even smaller jar file. - Internal and API code is obfuscated/optimized - This should be used if you want the best performance. - Even better performance.
```

**Comment by LoganDark** [comment]
where did you find that? because you should probably put it in the readme, or releases, or wiki, or somewhere

**Comment by 0-x-2-2** [comment]
> where did you find that? because you should probably put it in the readme, or releases, or wiki, or somewhere

Common sense. It also is written in the wiki afaik.

**Comment by LoganDark** [comment]
> Common sense

Dude how am I supposed to know that `-api` is the ENTIRE Baritone with Forge support?

> It also is written in the wiki afaik.

Clicking wiki redirects me to the readme lol

**Comment by 0-x-2-2** [comment]
Yep already exists in the Setup guide. https://github.com/cabaletta/baritone/blob/master/SETUP.md#artifacts

**Comment by 0-x-2-2** [comment]
> Dude how am I supposed to know that `-api` is the ENTIRE Baritone with Forge support?

Reading the SETUP guide...

**Comment by LoganDark** [comment]
> That is also wrong -api-forge is the forge version of the API jar.

Whatever dude, I don't know everything, don't act surprised when I don't know something

**Comment by 0-x-2-2** [comment]
> Whatever dude, I don't know everything, don't act surprised when I don't know something

The same guide that shows how to SETUP the dev environment actually contains this information. https://github.com/cabaletta/baritone/blob/master/SETUP.md#artifacts

**Comment by LoganDark** [comment]
I didn't even read the setup guide dude, I just used gradle like I would any other project. I didn't know to check the setup guide to see what the build outputs. Seemed unrelated to me. So that issue's solved.

**Comment by ZeroMemes** [comment]
Before this is merged, I'd like to work on moving more things to the `main` sourceset from `api`.

Immediately, I think it would be a good idea to separate `ArgConsumer` into an `IArgConsumer` `api` interface, and `ArgConsumer` `main` implementation. This should never be constructed by developers using the API, so it shouldn't be an issue. Provided there is comprehensive documentation for `IArgConsumer`, there will also be no need for developers to look at the implementation.

**Pull request merged**
