### PR TITLE
Change default behavior to no longer break beds

### PR DESCRIPTION
**Pull request by fw4hre0xxq**
Currently, if you use waypoints to go back to your bed, your bed will be broken, which could be very very bad if you're far from spawn.

Can I OwO if I'm a furry?

### CODE REVIEW

**Comment by S-B99** [comment]
mfw formatting scuffed

**Comment by S-B99** [comment]
does this even work? Beds after 1.13 have different names for their colors

**Comment by cookiedragon234** [comment]
He’s referencing it by block instance, not by string. Different colours of beds are instances of the same bed block, even if their names are slightly different.

**Comment by fw4hre0xxq** [comment]
I'm going to clean up commit history and make a new pr.

**Pull request closed without merging**
