### PR TITLE
add range to mining.

### PR DESCRIPTION
**Pull request by scorbett123**
This adds a range argument to mining.

Any suggestions of how to improve the command please say. Currently it is, #mine ["radius" ["home"] distance] [quantity] block1 ...

Based from #2054.

### CODE REVIEW

**Comment by scorbett123** [comment]
Closing in favour of #2088

**Comment by avneh** [comment]
sdd

**Comment by derBobo** [comment]
oh didn't see someone already created a pr for that

**Comment by scorbett123** [comment]
Don't worry, your implementation is much cleaner.

**Comment by avneh** [comment]
ya i think you should use filtration instead of full so it doesnt crash

**Comment by avneh** [comment]
basically it should only build with the items you have marked

**Comment by scorbett123** [comment]
What?

**Comment by avneh** [comment]
basically the player should choose what they want to use like if they wer
surrounded by dirt but they wanted cobblestone the dirt would and stuff
would be invis but you see cobble

**Comment by avneh** [comment]
or you could turn x into y

**Comment by avneh** [comment]
x = anything y = anything

**Comment by derBobo** [comment]
am i the only one who is confused by avnehs comments ?

**Comment by avneh** [comment]
no their are others

**Pull request closed without merging**
