### PR TITLE
actually fix mine under 0 height

### PR DESCRIPTION
**Pull request by wagyourtail**

### CODE REVIEW

**Review by ZacSharp — APPROVED** [review]

**Comment by leijurv** [comment]
ugh all this y stuff is so botched

**Comment by kubaaa203** [comment]
Where do I paste the code? There is no fasterworldscanner.java

**Comment by end-user** [comment]
Can this get merged to 1.20.2?

**Comment by ZacSharp** [comment]
[No?](https://github.com/cabaletta/baritone/pull/4172)

**Pull request merged**
