### PR TITLE
more intuitive smooth look/free look settings

### PR DESCRIPTION
**Pull request by babbaj**

### CODE REVIEW

**Comment by ZacSharp** [comment]
Doesn't this break the `freeLook` setting by always behaving as if it was enabled?

**Comment by babbaj** [comment]
no

**Comment by ZacSharp** [comment]
So `Target.Mode` didn't even make it into a release before becoming a lie. Love it how fast code can degrade.
(request rotation with `freeLook` disabled and no `blockInteract` and `antiCheatCompatibility` disabled, mode will be `Target.Mode.NONE` despite the rotations being shown clientside)

**Comment by leijurv** [comment]
lol

**Comment by leijurv** [comment]
no longer a lie???? real?????????

**Review by ZeroMemes — APPROVED** [review]

**Pull request merged**
