### PR TITLE
Merge 1.18.2 into 1.19.1

### PR DESCRIPTION
**Pull request by ZacSharp**
@rycbar0 what about the litematic version?
@wagyourtail please fix runClient on forge/tweaker on 1.16+

### CODE REVIEW

**Comment by wagyourtail** [comment]
used to work
doesn't matter anyway
you know tweaker's custom and not really supported, right?

once I add mixin remapping to https://github.com/wagyourtail/unimined I'll migrate to that and it'll clean things up a bit

**Comment by rycbar0** [comment]
1.18 and 1.19 have the same .litematic version (version 6)

**Comment by ZacSharp** [comment]
> used to work

Can't remember Forge runClient working.

> you know tweaker's custom and not really supported, right?

Then that's Forge left. I can live without tweaker (though it's really nice for testing. None of the modlaunchers meets that startup speed)

**Comment by wagyourtail** [comment]
> None of the modlaunchers meets that startup speed

fabric's pretty close, as it's not doing much more

**Pull request merged**
