### PR TITLE
Reliably clear keys when paused

### PR DESCRIPTION
**Pull request by ZacSharp**

### CODE REVIEW

**Comment by wagyourtail** [comment]
Doesnt pausing remove the input override handler anyway?

**Comment by ZacSharp** [comment]
`PathingBehavior` clears all keys after the first tick where a pause is requested (the first tick that is actually paused), which clears the keys *almost* always and reliably works for pure pathing processes.
However if you use something like `BuilderProcess` there are situation where the process presses down a key and requests a pause, so when control transfers to `#pause` then the pathing command is already `REQUEST_PAUSE` and `PathingBehavior` does *not* clear anything.
This is especially annoying if it happens with wasd or shift, because those keys are the trigger for Baritone blocking user input.

**Comment by ZacSharp** [comment]
Actually, you can't rely on inputs *not* being cleared already so why not add this to `InputOverrideHandler.onTick` instead?
I don't know of anything using the input system that does not unconditionally clear keys while it is running and `BackfillProcess` even does it while idling.

**Comment by ZacSharp** [comment]
> Actually, you can't rely on inputs not being cleared already so why not add this to `InputOverrideHandler.onTick` instead?

Because `InputOverrideHandler.onTick` is called before Minecraft reads the movement inputs so it would stop wasd, shift and space from working.

**Comment by leijurv** [comment]
lol this is so #3565

**Pull request merged**
