### PR TITLE
fix 1.19 build failing

### PR DESCRIPTION
**Pull request by wagyourtail**

### CODE REVIEW

**Comment by ZacSharp** [comment]
What is the difference to #4246?

**Comment by wagyourtail** [comment]
the difference is I ping'd leijurv in discord after he complained about it not building 

also, I put the version in 1 place so it's easier to change

**Comment by ZacSharp** [comment]
> also, I put the version in 1 place so it's easier to change

Where's the second place in my pr?

**Comment by leijurv** [comment]
sorry zacsharp

wagyourtail is correct, the only reason why I merged this one is that I got a ping on Discord for it

**Comment by ZacSharp** [comment]
I know you don't look here often and if wagyourtail asks you to merge a simple pr I can perfectly understand you not hunting for duplicates first. What irritated me is that wagyourtail apparently didn't see the duplicate, not that you merged this one.

**Comment by wagyourtail** [comment]
sorry. I usually fix things before checking to see if other people have already done it.

for example... https://github.com/Vineflower/vineflower/pull/337. I went through all that effort, and then checked and saw it was already done and merged in dev, just not on the stable release

**Pull request merged**
