### PR TITLE
1.20.4

### PR DESCRIPTION
**Pull request by wagyourtail**
\+ neoforge

### CODE REVIEW

**Comment by TherealONE12** [comment]
Where to download?

**Comment by ZacSharp** [comment]
For example like this

https://github.com/cabaletta/baritone/assets/68165024/7a551ae1-d77f-477e-ae3e-0b83bd1e99fd

**Comment by wb1016** [comment]
#mine command not working

**Comment by wb1016** [comment]
yeah. #mine does not work, definitely. JVM crashes.

**Comment by ZacSharp** [comment]
@wb1016 can you please open a new issue with more details?

**Comment by Aculoss** [comment]
Because #mine is just mine

**Pull request merged**
